### ISSUE TITLE
use_sdr and zeta parameters unused?

### ISSUE THREAD

**Issue by pzelasko** [noahfl/sdr-densenet-pytorch#1]
I've looked through densenet.py and didn't notice any usage of these variables after they get passed into the constructor - am I missing something? Where is the SDR logic?

**Comment by noahfl** [comment]
The vast majority of the SDR code is implemented in train.py due to the need to access modeparameters() to update the weights. I'm on mobile right now so this formatting may be wrong but the SDR portion of the code starts at the line linked below:

https://github.com/noahfl/sdr-densenet-pytorch/blob/c23b70a01065f9ebfd5f4571fddea614633b10e5/train.py#L238

**Comment by pzelasko** [comment]
Thanks, that helped. I was reading from my mobile too so it was more
difficult to find ;)

pon., 11 lut 2019, 23:44: Noah Frazier-Logue <notifications@github.com>
napisał(a):
